// Records a real, complete day from energy-charts.info as the built-in fixture.
// Writes: public/fixtures/day.json (client) + api/_lib/fixture-data.js (serverless fallback).
// Usage: node scripts/record-fixture.mjs [YYYY-MM-DD]   (default: yesterday, Europe/Berlin)

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const BASE = 'https://api.energy-charts.info';

// --- pick the day (Europe/Berlin) ---
const argDay = process.argv[2];
const now = new Date();
const berlinDate = (d) =>
  new Intl.DateTimeFormat('en-CA', { timeZone: 'Europe/Berlin', year: 'numeric', month: '2-digit', day: '2-digit' }).format(d);
const day = argDay || berlinDate(new Date(now.getTime() - 24 * 3600 * 1000));

// Berlin UTC offset for that day (July = +2, but compute properly)
function berlinMidnightUTC(dayStr) {
  // find UTC timestamp where Berlin local time is dayStr 00:00
  const guess = new Date(`${dayStr}T00:00:00Z`).getTime();
  for (let offH = -3; offH <= 3; offH++) {
    const t = guess - offH * 3600 * 1000;
    const fmt = new Intl.DateTimeFormat('en-CA', {
      timeZone: 'Europe/Berlin', year: 'numeric', month: '2-digit', day: '2-digit',
      hour: '2-digit', minute: '2-digit', hour12: false,
    }).format(new Date(t));
    if (fmt.startsWith(dayStr) && fmt.includes('00:00')) return Math.floor(t / 1000);
  }
  throw new Error('could not resolve Berlin midnight for ' + dayStr);
}

const startTs = berlinMidnightUTC(day);
const endTs = startTs + 24 * 3600;

async function get(path, params) {
  const url = new URL(BASE + path);
  for (const [k, v] of Object.entries(params)) url.searchParams.set(k, String(v));
  const res = await fetch(url, { signal: AbortSignal.timeout(30000) });
  if (!res.ok) throw new Error(`${path} -> HTTP ${res.status}`);
  return res.json();
}

const round = (x, d = 1) => (x == null ? null : Math.round(x * 10 ** d) / 10 ** d);

console.log(`Recording fixture for ${day} (Berlin) — unix ${startTs}..${endTs}`);

const [power, price, freq] = await Promise.all([
  get('/public_power', { country: 'de', start: startTs, end: endTs }),
  get('/price', { bzn: 'DE-LU', start: startTs, end: endTs }),
  // 30-min real frequency window from that day's evening (20:00–20:30 Berlin), loopable
  get('/frequency', { region: 'DE-Freiburg', start: startTs + 20 * 3600, end: startTs + 20.5 * 3600 }),
]);

const byName = {};
for (const t of power.production_types) byName[t.name] = t.data;
const n = power.unix_seconds.length;
const zeros = () => new Array(n).fill(0);
const pick = (name) => byName[name] || zeros();
const sum = (...names) =>
  power.unix_seconds.map((_, i) => {
    let s = 0;
    for (const nm of names) { const v = (byName[nm] || [])[i]; if (v != null) s += v; }
    return round(s);
  });
const one = (name) => pick(name).map((v) => round(v));

const series = {
  solar: one('Solar'),
  wind_onshore: one('Wind onshore'),
  wind_offshore: one('Wind offshore'),
  biomass: one('Biomass'),
  hydro: sum('Hydro Run-of-River', 'Hydro water reservoir'),
  pumped_gen: one('Hydro pumped storage'),
  pumped_consumption: one('Hydro pumped storage consumption'),
  fossil: sum('Fossil brown coal / lignite', 'Fossil hard coal', 'Fossil gas', 'Fossil oil', 'Fossil coal-derived gas'),
  load: one('Load'),
  re_share: pick('Renewable share of generation').map((v) => round(v, 1)),
};

const fixture = {
  meta: {
    kind: 'stromland-fixture',
    day,
    recorded_at: new Date().toISOString(),
    source: 'energy-charts.info (Fraunhofer ISE), CC BY 4.0',
    note: 'Real recorded day. Used as Archiv-Modus when live data is unavailable.',
  },
  power: { unix_seconds: power.unix_seconds, series },
  price: { unix_seconds: price.unix_seconds, value: price.price.map((v) => round(v, 2)), unit: price.unit },
  frequency: { unix_seconds: freq.unix_seconds, data: freq.data },
};

const json = JSON.stringify(fixture);
writeFileSync(join(ROOT, 'public/fixtures/day.json'), json);
writeFileSync(
  join(ROOT, 'api/_lib/fixture-data.js'),
  '// AUTO-GENERATED by scripts/record-fixture.mjs — real recorded day, do not edit.\n' +
    'export default ' + json + ';\n'
);

console.log(`OK — ${n} power points, ${price.price.length} price points, ${freq.data.length} freq samples`);
console.log(`day.json: ${(json.length / 1024).toFixed(0)} KB`);
